#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_PRINTK y
#define CONFIG_KERNEL_NAME "Peanut Kernel"
#define CONFIG_KERNEL_VERSION "0.0.1-alpha"
#define CONFIG_INIT_PATH "/sbin/init"
#define CONFIG_VM y
#define CONFIG_SLAB_ALLOCATOR y
#define CONFIG_KASLR y
#define CONFIG_SCHED_RR y
#define CONFIG_SCHED_MAX_PROCS 2000
#define CONFIG_TTY y
#define CONFIG_STORAGE_NVME y
#define CONFIG_NET_WIFI y
#define CONFIG_BLOCK_RAID y
#define CONFIG_NET_TCP_IP y
#define CONFIG_NET_E1000 y
#define CONFIG_NET_RTL8139 y
#define CONFIG_NET_RTL8169 y
#define CONFIG_NET_VIRTIO y
#define CONFIG_AUDIO_AC97 y
#define CONFIG_AUDIO_HDA y
#define CONFIG_STORAGE_IDE y
#define CONFIG_STORAGE_AHCI y
#define CONFIG_STORAGE_TESTS y
#define CONFIG_USB_XHCI y
#define CONFIG_INPUT_PS2 y
#define CONFIG_VIDEO_HDMI y
#define CONFIG_VGA_TEXT y
#define CONFIG_VGA_COLOR 0x0F
#define CONFIG_FS_FAT12_READ y
#define CONFIG_FS_FAT12_WRITE y
#define CONFIG_FS_FAT16_READ y
#define CONFIG_FS_FAT16_WRITE y
#define CONFIG_FS_FAT32_READ y
#define CONFIG_FS_FAT32_WRITE y
#define CONFIG_FS_EXFAT_READ y
#define CONFIG_FS_EXFAT_WRITE y
#define CONFIG_FS_EXT4_READ y
#define CONFIG_FS_EXT4_WRITE y
#define CONFIG_NETWORK_SYSCALLS y
#define CONFIG_DNS_RESOLVER y
#define CONFIG_ELF_LOADER y

#ifdef CONFIG_MANTAINER_MENTAL_STABILITY
#define CONFIG_MANTAINER_MENTAL_STABILITY y
#endif

#endif
